# Generated by Django 3.0.7 on 2020-08-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substitute',
            name='product_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_original', to='products.Product'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='product_substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
