# Generated by Django 3.0.7 on 2020-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200815_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
