# Generated by Django 3.0.7 on 2020-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200816_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
