# Generated by Django 3.0.7 on 2020-08-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200816_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='products.Product'),
        ),
    ]
