# Generated by Django 3.0.7 on 2020-08-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_substitute_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='product_id',
        ),
    ]
